echo "i am $(uname -r)"
echo "this is my shell"
echo "jenkins automation using webhook"
echo "automation"
echo "today is $(date)"
echo "no of cpu is $(nproc)"
echo "no of cpu is $(nproc)"
echo "no of cpu is $(nproc)"
